version: '2'
services:
  db:
    restart: always
    image: postgres:9.5.2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./env/development.env
  redis:
    restart: always
    image: redis:3.2.1
    ports:
     - "6379:6379"
  celery:
    build: .
    command: celery -A tracker worker -B -l info
    volumes:
      - .:/code
    links:
     - db
     - redis
    restart: always
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=tracker.settings.dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - redis
    env_file:
      - ./env/development.env
volumes:
  pgdata:
    driver: local