version: '2'
services:

  db:
    restart: always
    image: postgres:9.5.2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./env_files/production.env

  redis:
    restart: always
    image: redis:3.2.1
    ports:
     - "6379:6379"

  celery:
    build: .
    command: celery -A tracker worker -B -l info
    links:
      - db
      - redis
    restart: always
    env_file:
      - ./env_files/production.env

  web:
    build: .
    entrypoint: /code/run_server_production.sh
    ports:
      - "8000:8000"
    volumes:
      - /code/static
    links:
      - db
      - redis
    env_file:
      - ./env_files/production.env

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - web
    volumes_from:
      - web

volumes:
  pgdata:
    driver: local