# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='result_page_url',
            new_name='results_page_url',
        ),
    ]
